import Head from 'next/head';
import Image from 'next/image';
import { Toaster } from 'react-hot-toast';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <Toaster />
      </div>
    </div>
  );
}
